typography_spectrum: 0.9561412977054715
color:
  brandStrength: 0.07033325196243823
  lightness: 0.2725409537088126
  saturation: 0.8656388018280268
  rhythmicContrast: 0.40377215342596173
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
layout_spectrum: 0.10448019998148084
author:
  name: Nick Jones
  url: 'http://narrowdesign.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/efc98057-5758-4c6f-a74e-81e810c1b46b.png
name: The Culture of Motorized Bicycles
style: the-composer
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/36d76367-52a8-4f20-8c37-ec07d96612e6.png
title: The Culture of Motorized Bicycles
