typography_spectrum: 0.0745082141365856
color:
  brandStrength: 0.321415014564991
  lightness: 0.06322111189365387
  saturation: 0.8938799493480474
  rhythmicContrast: 0.5858410084620118
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
layout_spectrum: 0.7461054660379887
author:
  name: Nick Jones
  url: 'http://narrowdesign.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/efc98057-5758-4c6f-a74e-81e810c1b46b.png
name: The Culture of Motorized Bicycles
style: the-composer
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/36d76367-52a8-4f20-8c37-ec07d96612e6.png
title: The Culture of Motorized Bicycles
