typography_spectrum: 0.0745082141365856
color:
  brandStrength: 0.321415014564991
  lightness: 0.06322111189365387
  saturation: 0.8938799493480474
  rhythmicContrast: 0.5858410084620118
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
layout_spectrum: 0.7461054660379886
author:
  name: Nick Jones
  url: 'http://narrowdesign.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/efc98057-5758-4c6f-a74e-81e810c1b46b.png
name: The Culture of Motorized Bicycles
style: the-composer
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b5ca5841-0f36-4c3a-8836-25433f661d22.png
title: The Culture of Motorized Bicycles
description: Two Wheels. No Cares.
purpose:
  - id: d3b2f448-14f8-412f-a06d-37383e3ed1cb
    type: external
    value: 'http://twitter.com/narrowd'
    label: Design Tweets
